### PR TITLE
Using premake instead of prebuild

### PR DESCRIPTION
**Pull request by nooperation**

### CODE REVIEW

**Comment by SignpostMarv** [comment]
pr has conflicts ?

**Comment by nooperation** [comment]
Ah I kind of let this one get a bit stale ^^;. Will fix later on - mainly wanted to see if anyone was opposing a move to premake (active development and fairly widely used) instead of prebuild (no longer developed).

Would definitely like some testing to see how things go on other systems

**Comment by SignpostMarv** [comment]
Does premake do anything prebuild doesn't ?

**Comment by nooperation** [comment]
**Pros:**
- Out of the box support for visual studio 2015
- Under continuous development (Last official release of prebuild was 8 years ago)
- Is documented and has a community around it (I can't find any documentation for prebuild online)
- Fairly widespread usage

**Cons:**
- Will require a little more testing on other operating systems to make sure everything builds just fine
- It's a new system

**Comment by fennectech** [comment]
this looks like it would require alteration of my build script    id like to know if i am correct because changing the build system seems to be quite a big task

**Comment by fennectech** [comment]
https://aur.archlinux.org/packages/radegast-git/

**Comment by nooperation** [comment]
> bash runprebuild.sh
The name of the script is still the same in this merge request so it should still work fine (:

I'm still somewhat on the fence about this just because there could be others with their own build systems out there as well so it won't be merged for a good while (if it is merged)

**Comment by fennectech** [comment]
i tested it    everything went perfectly    if there are any things that need to be tested   leme know

**Comment by nooperation** [comment]
Closing and re-opening with development branch as the target (why doesn't github support this feature?)

**Comment by fennectech** [comment]
did we throw this out?  I thought it was a great idea  and didnt see any problems with it     so long as we make sure the guys downstream know of the comming change and can still sucessfuly build     it should be okay

**Comment by nooperation** [comment]
Nope, I'm going to reopen it once I setup a correct development branch for a more proper git flow. Apparently I can't just edit what the merge request is targeting like on gitlab : (

**Comment by fennectech** [comment]
oooh i see     so big things will go into radegast-testing first    where they are proven stable before being pushed down to the stable branch

**Comment by nooperation** [comment]
Yep! In general features are merged into a development branch and at some point in time the development branch is frozen and thoroughly tested. Once it's deemed suitable for release then it's merged into master and development is unfrozen. Though mostly it ends up being a bunch of people merging directly into master though (:

**Pull request closed without merging**
